### ISSUE TITLE
哈哈我也刚刚造了个类似的轮子

### ISSUE THREAD

**Issue by micln** [DropFan/go-sqlbuilder#1]
https://github.com/Kretech/Loulan/blob/master/src/test/java/net/romatic/query/QueryBuilderTest.java

本来也是计划用Go做，但是很多地方没想好，怕搞出来太啰嗦。就先曲线救国了。

学长新年快乐~

**Comment by DropFan** [comment]
还没造完我就后悔了。。时间都浪费在挖坑了
